name: CI/CD for SkyCave CaveService, deploying to AWS staging environment after running test suites.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  AWS_STAGE_CI_TEST: ci-test
  AWS_STAGE_STAGING: staging
  NODE_VERSION: "12"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Deploy to stage "${{ env.AWS_STAGE_CI_TEST }}"
        run: npm run sls -- deploy --region $AWS_REGION --stage $AWS_STAGE_CI_TEST
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run integration tests
        run: npm run test
        
      - name: Run acceptance tests
        run: npm run acceptance

      - name: Remove from stage "${{ env.AWS_STAGE_CI_TEST }}"
        run: npm run sls -- remove --region $AWS_REGION --stage $AWS_STAGE_CI_TEST
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-to-staging:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Deploy to stage "${{ env.AWS_STAGE_STAGING }}"
        run: npm run sls -- deploy --region $AWS_REGION --stage $AWS_STAGE_STAGING
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


